// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB33foO_zj4rjEllwxp3bAvHFc0UDpDYJM',
    appId: '1:669179933275:web:94df9b48e4e0570e35c57e',
    messagingSenderId: '669179933275',
    projectId: 'studyplanner-69823',
    authDomain: 'studyplanner-69823.firebaseapp.com',
    storageBucket: 'studyplanner-69823.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4GJKSKT7cIRF6BFG71ikYrq-niw0JNE',
    appId: '1:669179933275:android:4ff8cb75bf4f165b35c57e',
    messagingSenderId: '669179933275',
    projectId: 'studyplanner-69823',
    storageBucket: 'studyplanner-69823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQ25BRsp3wmc5ejCKH2TvQJfeCSYqA5w',
    appId: '1:669179933275:ios:1797bd63fd95d3fb35c57e',
    messagingSenderId: '669179933275',
    projectId: 'studyplanner-69823',
    storageBucket: 'studyplanner-69823.firebasestorage.app',
    iosBundleId: 'com.example.studyTimePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQ25BRsp3wmc5ejCKH2TvQJfeCSYqA5w',
    appId: '1:669179933275:ios:1797bd63fd95d3fb35c57e',
    messagingSenderId: '669179933275',
    projectId: 'studyplanner-69823',
    storageBucket: 'studyplanner-69823.firebasestorage.app',
    iosBundleId: 'com.example.studyTimePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB33foO_zj4rjEllwxp3bAvHFc0UDpDYJM',
    appId: '1:669179933275:web:b669dafdd51607a235c57e',
    messagingSenderId: '669179933275',
    projectId: 'studyplanner-69823',
    authDomain: 'studyplanner-69823.firebaseapp.com',
    storageBucket: 'studyplanner-69823.firebasestorage.app',
  );
}
